export const nutritionFields = [
    { name: "Calories", unit: "", indent: 0 },
    { name: "Total Fat", unit: "g", indent: 0 },
    { name: "Saturated", unit: "g", indent: 1 },
    { name: "Polyunsaturated", unit: "g", indent: 1 },
    { name: "Monounsaturated", unit: "g", indent: 1 },
    { name: "Trans", unit: "g", indent: 1 },
    { name: "Cholesterol", unit: "mg", indent: 0 },
    { name: "Sodium", unit: "mg", indent: 0 },
    { name: "Total Carbs", unit: "g", indent: 0 },
    { name: "Dietary Fiber", unit: "g", indent: 1 },
    { name: "Total Sugars", unit: "g", indent: 1 },
    { name: "Added Sugar", unit: "g", indent: 2 },
    { name: "Protein", unit: "g", indent: 0 },
    { name: "Vitamin D", unit: "mcg", indent: 0 },
    { name: "Iron", unit: "mg", indent: 0 },
    { name: "Calcium", unit: "mg", indent: 0 },
    { name: "Potassium", unit: "mg", indent: 0 },
]